version: "3.8"

services:
  service:
    build:
      context: .
      target: web
    command: node colonies
    restart: always
    ports:
      - "80:5000"
    networks:
      - colonies

networks:
  colonies:
