version: "3.8"

services:
  service:
    build:
      context: .
      target: service
    volumes:
      - ./service:/service
      - /service/node_modules
    command: node colonies
    restart: always
    ports:
      - "5000:5000"
    networks:
      - colonies

  client:
    build:
      context: .
      target: client-install
    command: npm run dev
    volumes:
      - ./client:/client
      - /client/node_modules
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VUE_APP_SOCKET_URI=http://localhost:5000
    networks:
      - colonies

networks:
  colonies:
