// colonies service
// Ben Hussey and Francesco Anselmo - May - August 2017

// Controller IPs defined here
var CONTROLLERS = [
  "192.168.10.100",
  "192.168.10.101",
  "192.168.10.102",
  "192.168.10.103",
  "192.168.10.104",
  "192.168.10.105",
];

// Segment map defined below according to this diagram

/*
 *    0  1  2  3  4  5  6  7  8  9 10 11 12 13 14
 *  0 o --- o --- o --- o --- o --- o --- o --- o
 *  1 |     |     |     |     |     |     |     |
 *  2 o --- o --- o --- o --- o --- o --- o --- o
 *  3 |     |     |     |     |     |     |     |
 *  4 o --- o --- o --- o --- o --- o --- o --- o
 *  5 |     |     |     |     |     |     |     |
 *  6 o --- o --- o --- o --- o --- o --- o --- o
 *  7 |     |     |     |     |     |     |     |
 *  8 o --- o --- o --- o --- o --- o --- o --- o
 *
 */

// Each row and col should be assigned to a controller strip and sequence
// Blocks should not be assigned to controllers (odd columns in odd rows)
var SEGMENTS = [
  // ------------------------------------------------------
  // CONTROLLER 0

  {
    ip: CONTROLLERS[0],
    strip: 0,
    seq: 0,
    start: 0,
    end: 29,
    row: 8,
    col: 1,
  },
  {
    ip: CONTROLLERS[0],
    strip: 0,
    seq: 1,
    start: 30,
    end: 60,
    row: 8,
    col: 3,
  },
  {
    ip: CONTROLLERS[0],
    strip: 0,
    seq: 2,
    start: 61,
    end: 88,
    row: 8,
    col: 5,
  },
  {
    ip: CONTROLLERS[0],
    strip: 0,
    seq: 3,
    start: 89,
    end: 118,
    row: 8,
    col: 7,
  },
  {
    ip: CONTROLLERS[0],
    strip: 1,
    seq: 0,
    start: 0,
    end: 30,
    row: 4,
    col: 1,
  },
  {
    ip: CONTROLLERS[0],
    strip: 1,
    seq: 1,
    start: 31,
    end: 61,
    row: 4,
    col: 3,
  },
  {
    ip: CONTROLLERS[0],
    strip: 1,
    seq: 2,
    start: 62,
    end: 92,
    row: 4,
    col: 5,
  },
  {
    ip: CONTROLLERS[0],
    strip: 1,
    seq: 3,
    start: 93,
    end: 122,
    row: 4,
    col: 7,
  },
  {
    ip: CONTROLLERS[0],
    strip: 2,
    seq: 0,
    start: 0,
    end: 31,
    row: 6,
    col: 1,
  },
  {
    ip: CONTROLLERS[0],
    strip: 2,
    seq: 1,
    start: 32,
    end: 59,
    row: 6,
    col: 3,
  },
  {
    ip: CONTROLLERS[0],
    strip: 2,
    seq: 2,
    start: 60,
    end: 87,
    row: 6,
    col: 5,
  },
  {
    ip: CONTROLLERS[0],
    strip: 2,
    seq: 3,
    start: 88,
    end: 117,
    row: 6,
    col: 7,
  },

  // ------------------------------------------------------
  // CONTROLLER 1

  {
    ip: CONTROLLERS[1],
    strip: 0,
    seq: 0,
    start: 0,
    end: 31,
    row: 2,
    col: 1,
  },
  {
    ip: CONTROLLERS[1],
    strip: 0,
    seq: 1,
    start: 32,
    end: 59,
    row: 2,
    col: 3,
  },
  {
    ip: CONTROLLERS[1],
    strip: 0,
    seq: 2,
    start: 60,
    end: 90,
    row: 2,
    col: 5,
  },
  {
    ip: CONTROLLERS[1],
    strip: 0,
    seq: 3,
    start: 91,
    end: 120,
    row: 2,
    col: 7,
  },
  {
    ip: CONTROLLERS[1],
    strip: 1,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 0,
  },
  {
    ip: CONTROLLERS[1],
    strip: 1,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 0,
  },
  {
    ip: CONTROLLERS[1],
    strip: 1,
    seq: 2,
    start: 61,
    end: 90,
    row: 5,
    col: 0,
  },
  {
    ip: CONTROLLERS[1],
    strip: 1,
    seq: 3,
    start: 91,
    end: 120,
    row: 7,
    col: 0,
  },
  {
    ip: CONTROLLERS[1],
    strip: 2,
    seq: 0,
    start: 0,
    end: 27,
    row: 0,
    col: 1,
  },
  {
    ip: CONTROLLERS[1],
    strip: 2,
    seq: 1,
    start: 28,
    end: 55,
    row: 0,
    col: 3,
  },
  {
    ip: CONTROLLERS[1],
    strip: 2,
    seq: 3,
    start: 56,
    end: 85,
    row: 0,
    col: 5,
  },
  {
    ip: CONTROLLERS[1],
    strip: 2,
    seq: 2,
    start: 86,
    end: 115,
    row: 0,
    col: 7,
  },

  // ------------------------------------------------------
  // CONTROLLER 2

  {
    ip: CONTROLLERS[2],
    strip: 0,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 6,
  },
  {
    ip: CONTROLLERS[2],
    strip: 0,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 6,
  },
  {
    ip: CONTROLLERS[2],
    strip: 0,
    seq: 2,
    start: 61,
    end: 90,
    row: 5,
    col: 6,
  },
  {
    ip: CONTROLLERS[2],
    strip: 0,
    seq: 3,
    start: 91,
    end: 120,
    row: 7,
    col: 6,
  },
  {
    ip: CONTROLLERS[2],
    strip: 1,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 4,
  },
  {
    ip: CONTROLLERS[2],
    strip: 1,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 4,
  },
  {
    ip: CONTROLLERS[2],
    strip: 1,
    seq: 2,
    start: 61,
    end: 90,
    row: 5,
    col: 4,
  },
  {
    ip: CONTROLLERS[2],
    strip: 1,
    seq: 3,
    start: 91,
    end: 120,
    row: 7,
    col: 4,
  },
  {
    ip: CONTROLLERS[2],
    strip: 2,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 2,
  },
  {
    ip: CONTROLLERS[2],
    strip: 2,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 2,
  },
  {
    ip: CONTROLLERS[2],
    strip: 2,
    seq: 2,
    start: 61,
    end: 90,
    row: 5,
    col: 2,
  },
  {
    ip: CONTROLLERS[2],
    strip: 2,
    seq: 3,
    start: 91,
    end: 120,
    row: 7,
    col: 2,
  },

  // ------------------------------------------------------
  // CONTROLLER 3

  {
    ip: CONTROLLERS[3],
    strip: 0,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 12,
  },
  {
    ip: CONTROLLERS[3],
    strip: 0,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 12,
  },
  {
    ip: CONTROLLERS[3],
    strip: 0,
    seq: 2,
    start: 61,
    end: 90,
    row: 5,
    col: 12,
  },
  {
    ip: CONTROLLERS[3],
    strip: 0,
    seq: 3,
    start: 91,
    end: 120,
    row: 7,
    col: 12,
  },
  {
    ip: CONTROLLERS[3],
    strip: 1,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 8,
  },
  {
    ip: CONTROLLERS[3],
    strip: 1,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 8,
  },
  {
    ip: CONTROLLERS[3],
    strip: 1,
    seq: 2,
    start: 61,
    end: 90,
    row: 5,
    col: 8,
  },
  {
    ip: CONTROLLERS[3],
    strip: 1,
    seq: 3,
    start: 91,
    end: 120,
    row: 7,
    col: 8,
  },
  {
    ip: CONTROLLERS[3],
    strip: 2,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 10,
  },
  {
    ip: CONTROLLERS[3],
    strip: 2,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 10,
  },
  {
    ip: CONTROLLERS[3],
    strip: 2,
    seq: 2,
    start: 61,
    end: 90,
    row: 5,
    col: 10,
  },
  {
    ip: CONTROLLERS[3],
    strip: 2,
    seq: 3,
    start: 91,
    end: 120,
    row: 7,
    col: 10,
  },

  // ------------------------------------------------------
  // CONTROLLER 4

  {
    ip: CONTROLLERS[4],
    strip: 0,
    seq: 0,
    start: 0,
    end: 30,
    row: 1,
    col: 14,
  },
  {
    ip: CONTROLLERS[4],
    strip: 0,
    seq: 1,
    start: 31,
    end: 60,
    row: 3,
    col: 14,
  },
  {
    ip: CONTROLLERS[4],
    strip: 0,
    seq: 2,
    start: 61,
    end: 91,
    row: 5,
    col: 14,
  },
  {
    ip: CONTROLLERS[4],
    strip: 0,
    seq: 3,
    start: 92,
    end: 121,
    row: 7,
    col: 14,
  },
  {
    ip: CONTROLLERS[4],
    strip: 1,
    seq: 0,
    start: 0,
    end: 28,
    row: 0,
    col: 13,
  },
  {
    ip: CONTROLLERS[4],
    strip: 1,
    seq: 1,
    start: 29,
    end: 59,
    row: 0,
    col: 11,
  },
  {
    ip: CONTROLLERS[4],
    strip: 1,
    seq: 2,
    start: 60,
    end: 89,
    row: 0,
    col: 9,
  },
  {
    ip: CONTROLLERS[4],
    strip: 2,
    seq: 0,
    start: 0,
    end: 28,
    row: 2,
    col: 13,
  },
  {
    ip: CONTROLLERS[4],
    strip: 2,
    seq: 1,
    start: 29,
    end: 56,
    row: 2,
    col: 11,
  },
  {
    ip: CONTROLLERS[4],
    strip: 2,
    seq: 2,
    start: 57,
    end: 87,
    row: 2,
    col: 9,
  },

  // ------------------------------------------------------
  // CONTROLLER 5

  {
    ip: CONTROLLERS[5],
    strip: 0,
    seq: 0,
    start: 0,
    end: 30,
    row: 4,
    col: 13,
  },
  {
    ip: CONTROLLERS[5],
    strip: 0,
    seq: 1,
    start: 31,
    end: 62,
    row: 4,
    col: 11,
  },
  {
    ip: CONTROLLERS[5],
    strip: 0,
    seq: 2,
    start: 63,
    end: 92,
    row: 4,
    col: 9,
  },
  {
    ip: CONTROLLERS[5],
    strip: 1,
    seq: 0,
    start: 0,
    end: 31,
    row: 6,
    col: 13,
  },
  {
    ip: CONTROLLERS[5],
    strip: 1,
    seq: 1,
    start: 32,
    end: 59,
    row: 6,
    col: 11,
  },
  {
    ip: CONTROLLERS[5],
    strip: 1,
    seq: 2,
    start: 60,
    end: 90,
    row: 6,
    col: 9,
  },
  {
    ip: CONTROLLERS[5],
    strip: 2,
    seq: 0,
    start: 0,
    end: 28,
    row: 8,
    col: 13,
  },
  {
    ip: CONTROLLERS[5],
    strip: 2,
    seq: 1,
    start: 29,
    end: 56,
    row: 8,
    col: 11,
  },
  {
    ip: CONTROLLERS[5],
    strip: 2,
    seq: 2,
    start: 57,
    end: 88,
    row: 8,
    col: 9,
  },
];

exports.CONTROLLERS = CONTROLLERS;
exports.SEGMENTS = SEGMENTS;
